name: Create SDK update PR

on:
  workflow_dispatch:
    inputs:
      sdk_name:
        description: 'The SDK for which the version should be updated'
        required: true
        type: choice
        options:
          - android
          - ios
      version_number:
        description: 'The version number to which the SDK should be updated'
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git User
        run: |
          git config --global user.name "Update Bot"
          git config --global user.email "update-bot@bitmovin.com"

      - name: Set Update Branch name
        id: branching
        run: |
          branch_name="update_${{ inputs.sdk_name}}_player_to_${{ inputs.version_number }}"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

      - name: Create Update Branch
        run: |
          git push origin --delete ${{ steps.branching.outputs.branch_name }} || true
          git checkout -b ${{ steps.branching.outputs.branch_name }}

      - name: Bump iOS SDK version
        if: ${{ inputs.sdk_name == 'ios' }}
        run: |
          sed -i 's/s.dependency "BitmovinPlayer", ".*/s.dependency "BitmovinPlayer", "${{ inputs.version_number }}"/g' RNBitmovinPlayer.podspec

      - name: Bump Android SDK version
        if: ${{ inputs.sdk_name == 'android' }}
        run: |
          sed -i "s/com.bitmovin.player:player:.*/com.bitmovin.player:player:${{ inputs.version_number }}'/g" android/build.gradle

      - name: Commit version bump
        run: |
          git add RNBitmovinPlayer.podspec android/build.gradle
          git commit -m "chore(${{ inputs.sdk_name }}): update ${{ inputs.sdk_name }} player version to ${{ inputs.version_number }}"
          git push origin ${{ steps.branching.outputs.branch_name }}

      - name: Create PR
        run: |
          gh pr create \
          --base "${{ github.ref }}" \
          --title "Update ${{ inputs.sdk_name }} player to ${{ inputs.version_number }}" \
          --body "Automated ${{ inputs.sdk_name }} player version update to ${{ inputs.version_number }}"
