name: Start Release Train
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Next version number of the release'
        type: string
        required: true
      release_date:
        description: 'Date of the final release. Will be used for CHANGELOG.md (format YYYY-MM-DD, e.g. 2023-02-27)'
        type: string
        required: true
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
jobs:
  placeholder:
    name: Placeholder job
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "Placeholder step"
